import { Download, FileUp, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import Layout from '../components/Layout.jsx';
import DataTable from '../components/DataTable.jsx';
import { ErrorText, PageHeader } from '../components/Ui.jsx';
import { api } from '../api/axiosInstance.js';
import { useAuth } from '../context/AuthContext.jsx';

const types = ['CITIZENSHIP', 'PASSPORT', 'CONTRACT', 'OFFER_LETTER', 'WORK_PERMIT', 'OTHER'];
export default function Documents() {
  const { user } = useAuth(); const admin = user.role === 'ADMIN'; const [employees, setEmployees] = useState([]); const [employeeId, setEmployeeId] = useState(user.employeeId); const [rows, setRows] = useState([]); const [form, setForm] = useState({ docType: 'CITIZENSHIP', expiryDate: '', file: null }); const [error, setError] = useState('');
  async function loadEmployees() { if (admin) { const response = await api.get('/employees'); setEmployees(response.data); if (!employeeId && response.data[0]) setEmployeeId(response.data[0].id); } }
  async function loadDocuments(id = employeeId) { if (id) setRows((await api.get(`/employees/${id}/documents`)).data); }
  useEffect(() => { loadEmployees().catch((err) => setError(err.message)); }, []);
  useEffect(() => { loadDocuments().catch((err) => setError(err.message)); }, [employeeId]);
  async function upload(event) { event.preventDefault(); if (!form.file) return; const body = new FormData(); body.append('file', form.file); body.append('docType', form.docType); if (form.expiryDate) body.append('expiryDate', form.expiryDate); try { await api.post(`/employees/${employeeId}/documents`, body); setForm({ docType: 'CITIZENSHIP', expiryDate: '', file: null }); event.target.reset(); await loadDocuments(); } catch (err) { setError(err.message); } }
  async function remove(id) { if (!window.confirm('Delete this document?')) return; try { await api.delete(`/documents/${id}`); await loadDocuments(); } catch (err) { setError(err.message); } }
  return <Layout><PageHeader title="Documents" eyebrow="Employee records" description={admin ? 'Manage identity, contract, and permit files.' : 'Your uploaded employee records.'} />{admin && <label className="mb-4 block max-w-sm text-sm font-semibold">Employee<select className="field mt-2 w-full" value={employeeId} onChange={(e) => setEmployeeId(Number(e.target.value))}>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select></label>}{admin && <form className="card grid gap-4 p-5 md:grid-cols-4" onSubmit={upload}><label className="text-sm font-semibold">Document type<select className="field mt-2 w-full" value={form.docType} onChange={(e) => setForm({ ...form, docType: e.target.value })}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm font-semibold">Expiry date<input className="field mt-2 w-full" type="date" value={form.expiryDate} onChange={(e) => setForm({ ...form, expiryDate: e.target.value })} /></label><label className="text-sm font-semibold">File<input className="mt-2 block w-full text-sm" required type="file" onChange={(e) => setForm({ ...form, file: e.target.files[0] })} /></label><button className="btn btn-primary self-end"><FileUp size={16} /> Upload</button></form>}<ErrorText message={error} /><div className="mt-6"><DataTable testId="documents-table" rows={rows} getKey={(row) => row.id} columns={[{ key: 'fileName', label: 'File' }, { key: 'docType', label: 'Type' }, { key: 'uploadedAt', label: 'Uploaded', render: (row) => new Date(row.uploadedAt).toLocaleDateString() }, { key: 'expiryDate', label: 'Expiry', render: (row) => row.expiryDate ? new Date(row.expiryDate).toLocaleDateString() : '—' }, { key: 'actions', label: 'Actions', render: (row) => <div className="flex gap-2"><a className="btn btn-secondary h-8" href={`${api.defaults.baseURL.replace('/api', '')}/api/documents/${row.id}/download`}><Download size={14} /> Download</a>{admin && <button className="btn btn-danger h-8" onClick={() => remove(row.id)}><Trash2 size={14} /> Delete</button>}</div> }]} /></div></Layout>;
}
